package com.example.user.entity;
import jakarta.persistence.*;
@Entity @Table(name="tbl_dyn_employees") public class Employee extends com.example.audit.AuditedEntity {
    @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id;
    @Column(unique=true,nullable=false) public String code;
    public String name;
    @Column(unique=true,nullable=false) public String email;
    public String department;
    public String status;
    public String firstName;
    public String lastName;
    public String photoUrl;
    public String gender;
    public String phone;
    public String businessLocation;
    public String cashRegister;
    public String reportsTo;
    public String associatedEmailAccount;
    public String streetAddress;
    public String streetAddressLine2;
    public String city;
    public String state;
    public String county;
    public String country;
    public String zipCode;
    @Column(unique=true) public String loginId;
    public String thirdPartyLoginEmails;
    public String warehouse;
    public String workShift;
    public String holidaySchedule;
    @Column(columnDefinition="TEXT") public String customFields;
    public boolean hasLogin;
    public boolean maintainLoginHistory;
    public boolean viewOthersTimeCaptures;
    public boolean requireMfa;
    public boolean preventOthersTimeCapture;
    public boolean notAnEmployee;
    public boolean assignedToServices;
    public boolean captureInvoiceSignature;
    public boolean captureOrderSignature;
    public boolean deliverOrders;
    public boolean canHaveAppointments;
    public boolean performServices;
    public boolean seeRepeatServices;
    public boolean serviceLaborTimer;
    public Integer maximumDailyServices;
    @Column(precision=19,scale=6) public java.math.BigDecimal hourlyRate;
    @Column(precision=9,scale=6) public java.math.BigDecimal salesCommissionPercent;
    public java.time.LocalDate dateOfBirth;
    public java.time.LocalDate joiningDate;
    @ManyToOne @JoinColumn(name="role_id") public Role assignedRole;
    public String passwordHash;
    public long credentialVersion;
}
