<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>com.example</groupId><artifactId>microservices</artifactId><version>0.0.1-SNAPSHOT</version><packaging>pom</packaging><modules><module>common-audit</module><module>eureka-server</module><module>config-server</module><module>user-service</module><module>product-service</module><module>order-service</module><module>inventory-service</module><module>sales-invoice-service</module><module>api-gateway</module></modules></project>
