server:
  port: 8083
spring:
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
