export type Employee = {
  id: number;
  code: string;
  name: string;
  email: string;
  role: string;
  department: string;
  status: string;
  firstName?: string;
  lastName?: string;
  photoUrl?: string;
  gender?: string;
  dateOfBirth?: string;
  phone?: string;
  businessLocation?: string;
  joiningDate?: string;
  cashRegister?: string;
  reportsTo?: string;
  associatedEmailAccount?: string;
  streetAddress?: string;
  streetAddressLine2?: string;
  city?: string;
  state?: string;
  county?: string;
  country?: string;
  zipCode?: string;
  hasLogin?: boolean;
  loginId?: string;
  thirdPartyLoginEmails?: string;
  maintainLoginHistory?: boolean;
  viewOthersTimeCaptures?: boolean;
  requireMfa?: boolean;
  preventOthersTimeCapture?: boolean;
  notAnEmployee?: boolean;
  assignedToServices?: boolean;
  captureInvoiceSignature?: boolean;
  captureOrderSignature?: boolean;
  deliverOrders?: boolean;
  canHaveAppointments?: boolean;
  performServices?: boolean;
  seeRepeatServices?: boolean;
  serviceLaborTimer?: boolean;
  maximumDailyServices?: number;
  warehouse?: string;
  workShift?: string;
  hourlyRate?: number;
  salesCommissionPercent?: number;
  holidaySchedule?: string;
  customFields?: string;
};
// Password is write-only: never request or render it in employee responses.
export type EmployeeInput = Omit<Employee, 'id'> & { password?: string };
export const departments = ['Management', 'Sales', 'Purchase', 'Accounts', 'Support'];
export const roles = ['ADMIN', 'MANAGER', 'SALES', 'PURCHASE', 'EMPLOYEE'];
